# Generated by Django 5.2.7 on 2025-11-05 19:59

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(default=uploads.models.expire_time)),
                ('file', models.FileField(upload_to=uploads.models.upload_path)),
                ('title', models.CharField(max_length=120)),
                ('share_link', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('downloads', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
    ]
