# Generated by Django 5.2.7 on 2025-11-06 08:08

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='expire_date',
            field=models.DateTimeField(default=uploads.models.default_expire_time),
        ),
    ]
