# Generated by Django 5.2.7 on 2025-11-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_uploadedfile_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='downloads',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
