# Generated by Django 5.2.7 on 2025-11-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_remove_uploadedfile_downloads_uploadedfile_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='views',
        ),
    ]
